# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QStream
                                 A QGIS plugin
 The official plugin for the Stream Mesoscopic Traffic Simulator
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-29
        copyright            : (C) 2019 by CEREMA Centre-Est
        email                : aurelien.clairais@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QStream class from file QStream.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QStream import QStream
    return QStream(iface)
